# Generated by Django 4.1.7 on 2023-06-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_locality_orderplaced_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal')], default='Cash on Delivery', max_length=50),
        ),
    ]
